# fly.toml app configuration file generated for price-crawler on 2023-09-28T03:03:25+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "price-crawler"
primary_region = "sin"
swap_size_mb = 512

[build]

# [http_service]
# internal_port = 3000
# force_https = true
# auto_stop_machines = true
# auto_start_machines = true
# min_machines_running = 0
# processes = ["app"]
